# Docker Image Builder
# Author @KirsminX or @Kirsmin

name: Docker Image Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 使用 BuildX 构建
        uses: docker/setup-buildx-action@v2

      - name: 编译镜像
        run: |
          # 获取当前日期
          DATE=$(date +'%Y-%m-%d')

          # 使用 Docker BuildX 编译镜像
          docker buildx build --platform linux/amd64,linux/arm64 -t ssh-alert-server:$DATE -f src/docker/Dockerfile .

          # 将镜像保存为 tar 文件
          mkdir -p build
          docker save ssh-alert-server:$DATE -o build/$DATE.tar

      - name: 提交 Commit，推送文件
        run: |
          # 配置 git 用户
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 提交 tar 文件
          git add build/$DATE.tar
          git commit -m "<BUILD> 日期:$DATE 自动化构建 Docker 镜像"

          # 推送到远程仓库
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}